export const ROUTES = {
  HOME: "/",
  REGISTER: "/register",
  LOGIN: "/sign-in",
  RESET_PASSWORD: "/reset-password/:token",
  CHANGE_PASSWORD: "/change-password/:token",
  FORGET_PASSWORD: "/forgot-password",
  FRIENDS: "/friends",
  FRIENDS_NON: "/friends/non-friends",
  FRIENDS_REQUEST: "/friends/requests",
  SENDED_FRIENDS_REQUEST: "/friends/sended/requests",
  NOTIFICATIONS: "/notifications",
  PROFILE: "/profile",
  SETTINGS: "/settings",
};
